#!/bin/bash
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                                                                        "
echo "                                                                        "
echo "________________________________U_______________________________________"
sleep 1 
clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "                                                                        "
echo "                                *                                        "
echo "________________________________U_______________________________________"
sleep 0.5
clear
echo "                                                                          "
echo "                                                                          "
echo "                                                                          "
echo "                                                                        "
echo "                                                                        "
echo "                                                                      "
echo "                                                                      "
echo "                                                                     "
echo "                                                                       "
echo "                                                                        "
echo "                                                                       "
echo "                                *                                        "
echo "                                                                        "
echo "________________________________U_______________________________________"
sleep 0.5
clear
echo "                                                                          "
echo "                                                                          "
echo "                                                                          "
echo "                                                                        "
echo "                                                                        "
echo "                                                                      "
echo "                                                                      "
echo "                                                                     "
echo "                                                                       "
echo "                                                                        "
echo "                                *                                       "
echo "                                                                        "
echo "                                                                        "
echo "________________________________U_______________________________________"
sleep 0.5
clear
echo "                                                                          "
echo "                                                                          "
echo "                                                                          "
echo "                                                                        "
echo "                                                                        "
echo "                                                                      "
echo "                                                                      "
echo "                                                                     "
echo "                                                                       "
echo "                                *                                        "
echo "                                                                       "
echo "                                                                        "
echo "                                                                        "
echo "________________________________U_______________________________________"
sleep 0.5
clear
echo "                                                                          "
echo "                                                                          "
echo "                                                                          "
echo "                                                                        "
echo "                                                                        "
echo "                                                                      "
echo "                                                                      "
echo "                                                                     "
echo "                                *                                       "
echo "                                                                        "
echo "                                                                       "
echo "                                                                        "
echo "                                                                        "
echo "________________________________U_______________________________________"
sleep 0.5
clear
echo "                                                                          "
echo "                                                                          "
echo "                                                                          "
echo "                                                                        "
echo "                                                                        "
echo "                                                                      "
echo "                                                                      "
echo "                                *                                     "
echo "                                                                       "
echo "                                                                        "
echo "                                                                       "
echo "                                                                        "
echo "                                                                        "
echo "________________________________U_______________________________________"
sleep 0.5
clear
echo "                                                                          "
echo "                                                                          "
echo "                                                                          "
echo "                                                                        "
echo "                                                                        "
echo "                                                                      "
echo "                                *                                      "
echo "                                                                     "
echo "                                                                       "
echo "                                                                        "
echo "                                                                       "
echo "                                                                        "
echo "                                                                        "
echo "________________________________U_______________________________________"
sleep 0.5
clear
echo "                                                                          "
echo "                                                                          "
echo "                                                                          "
echo "                                                                        "
echo "                                                                        "
echo "                                                                      "
echo "                                $                                      "
echo "                                                                     "
echo "                                                                       "
echo "                                                                        "
echo "                                                                       "
echo "                                                                        "
echo "                                                                        "
echo "________________________________U_______________________________________"
sleep 0.5
clear
echo "                                                                          "
echo "                                                                          "
echo "                                                                          "
echo "                                                                        "
echo "                                                                        "
echo "                               ****                                   "
echo "                              **%%%**                                     "
echo "                               *****                                   "
echo "                                                                       "
echo "                                                                        "
echo "                                                                       "
echo "                                                                        "
echo "                                                                        "
echo "________________________________U_______________________________________"
sleep 1
clear
echo "                                                                          "
echo "                                                                          "
echo "                                                                          "
echo "                                                                        "
echo "                                                                        "
echo "                                 **                                    "
echo "                              * **** *                                     "
echo "                            * ** ** **  *                                  "
echo "                              * ****  *                                     "
echo "                                 **                                       "
echo "                                                                       "
echo "                                                                        "
echo "                                                                        "
echo "________________________________U_______________________________________"
sleep 1
clear
echo "                                                                          "
echo "                                                                          "
echo "                                                                          "
echo "                                                                        "
echo "                                                                ***   * *  "
echo "         ***    * *   *     *   ***    ****      *     *****   *   *  * *           "
echo "        *      *   *  * *   *  *       *   *    * *      *      *     * *    "
echo "        *      *   *  *   * *  *  ***  * **    *****     *    *   *      "
echo "         ***    * *   *     *   ****   *   *  *     *    *     ***    * *         "
echo "                                                                        "
echo "                                                                       "
echo "                                                                        "
echo "                                                                        "
echo "________________________________U_______________________________________"
sleep 3
clear
